services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

    env_file:
      - .env

    working_dir: /var/www

    ports:
      - "8000:8000"

    command: >
      php artisan octane:start --server=swoole --host=0.0.0.0 --port=8000 --workers=auto --task-workers=auto

    networks:
      - test-vecipaya

  reverb:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

    env_file:
      - .env

    working_dir: /var/www

    ports:
      - "8080:8080"

    command: >
      php artisan reverb:start --host=0.0.0.0 --port=8080

    networks:
      - test-vecipaya

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

    env_file:
      - .env

    working_dir: /var/www

    command: >
      php artisan queue:work rabbitmq --sleep=1 --tries=3 --timeout=300

    networks:
      - test-vecipaya

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

    env_file:
      - .env

    working_dir: /var/www

    command: php artisan schedule:work

    networks:
      - test-vecipaya

networks:
  test-vecipaya:
    external: true
