[supervisord]
nodaemon=true

[program:php-fpm]
command=docker-php-entrypoint php-fpm
autostart=true
autorestart=true
stdout_logfile=/var/log/php-fpm.log
stderr_logfile=/var/log/php-fpm.err.log

[program:reverb]
command=npm start --prefix /var/www/reverb
autostart=true
autorestart=true
stdout_logfile=/var/log/reverb.log
stderr_logfile=/var/log/reverb.err.log
